In [1]:
import pandas as pd

In [2]:
df_sales = pd.DataFrame(columns=["Date", "Amount"])

df_sales

Empty DataFrame
Columns: [Date, Amount]
Index: []

In [3]:
new_data = {
    "Date": ["January 1", "January 2"],
    "Amount": [500.00, 600.00]
}

df_new_data = pd.DataFrame(new_data)

df_new_data

        Date  Amount
0  January 1   500.0
1  January 2   600.0

In [4]:
df_sales = pd.concat([df_sales, df_new_data])

df_sales

C:\Users\robfr\AppData\Local\Temp\ipykernel_11904\3338249085.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_sales = pd.concat([df_sales, df_new_data])

        Date  Amount
0  January 1   500.0
1  January 2   600.0

In [5]:
df_second = pd.DataFrame({
    "Date": ["January 3", "January 4"],
    "Amount": [100.00, 200.00]
})

In [6]:
df_second

        Date  Amount
0  January 3   100.0
1  January 4   200.0

In [7]:
df_new = pd.concat([df_sales, df_second])

df_new

        Date  Amount
0  January 1   500.0
1  January 2   600.0
0  January 3   100.0
1  January 4   200.0

In [8]:
df_new.reset_index(drop=True, inplace=True)

df_new

        Date  Amount
0  January 1   500.0
1  January 2   600.0
2  January 3   100.0
3  January 4   200.0

In [9]:
new_column_data = {
    "Location": ["Store A", "Store B"]
}

df_column_data = pd.DataFrame(new_column_data)

df_new = pd.concat([df_new, df_column_data], axis=1)

df_new

        Date  Amount Location
0  January 1   500.0  Store A
1  January 2   600.0  Store B
2  January 3   100.0      NaN
3  January 4   200.0      NaN