In [1]:
import pandas as pd

In [2]:
data = {
    "Date": ["1st Sept","2nd Sept","3rd Sept","4th Sept"],
    "Branch Name": ["Halifax", "TSB", "Lloyds", "Santander"],
    "Amount of Sales": [500.00, 675.00, 1050.00, 425.00],
    "Is Active": [True, True, False, True]
}

df_sales = pd.DataFrame(data)

df_sales

       Date Branch Name  Amount of Sales  Is Active
0  1st Sept     Halifax            500.0       True
1  2nd Sept         TSB            675.0       True
2  3rd Sept      Lloyds           1050.0      False
3  4th Sept   Santander            425.0       True

In [3]:
new_data = {
    "Number of Employees": [20,34,42,17]
}

df_new = pd.DataFrame(new_data)

In [4]:
df_new

   Number of Employees
0                   20
1                   34
2                   42
3                   17

In [10]:
df_combined = pd.concat([df_sales, df_new], axis=1)

df_combined

       Date Branch Name  Amount of Sales  Is Active  Number of Employees
0  1st Sept     Halifax            500.0       True                   20
1  2nd Sept         TSB            675.0       True                   34
2  3rd Sept      Lloyds           1050.0      False                   42
3  4th Sept   Santander            425.0       True                   17